{{- if .Values.inventoryApp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.inventoryApp.name }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.inventoryApp.name }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.inventoryApp.secret.dbPassword | b64enc | quote }}
{{- end }}