{{- if .Values.vault.enabled }}
---
# SecretStore - Conexão com o Vault
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: {{ .Values.global.namespace }}
spec:
  provider:
    vault:
      server: "http://vault.api-app-go.svc.cluster.local:8200"  # FQDN completo
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
---
# Secret com token do Vault (dev mode - em produção usar Kubernetes auth)
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  token: "root"
---
# ExternalSecret - Sincroniza secrets do Vault para Kubernetes
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-credentials
  namespace: {{ .Values.global.namespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: mysql-secrets
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: inventory-app/database
        property: MYSQL_ROOT_PASSWORD
    - secretKey: DB_PASSWORD
      remoteRef:
        key: inventory-app/database
        property: DB_PASSWORD
{{- end }}
