{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.grafana.name }}-datasources
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.grafana.name }}
  annotations:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
{{- if .Values.grafana.datasources.tempo.enabled }}
      - name: Tempo
        type: tempo
        access: proxy
        orgId: 1
        url: {{ .Values.grafana.datasources.tempo.url }}
        basicAuth: false
        isDefault: {{ .Values.grafana.datasources.tempo.isDefault | default true }}
        version: 1
        editable: true
        uid: tempo
        jsonData:
          httpMethod: GET
          serviceMap:
            datasourceUid: mimir
          tracesToLogs:
            datasourceUid: loki
            tags: ["job", "instance", "pod", "namespace", "app"]
{{- end }}
{{- if .Values.grafana.datasources.loki.enabled }}
      - name: Loki
        type: loki
        access: proxy
        orgId: 1
        url: {{ .Values.grafana.datasources.loki.url }}
        basicAuth: false
        isDefault: false
        version: 1
        editable: true
        apiVersion: 1
        uid: loki
        jsonData:
          maxLines: {{ .Values.grafana.datasources.loki.maxLines }}
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: '"trace_id":\s*"([a-f0-9]{32})"'
              name: TraceID
              url: "$${__value.raw}"
              urlDisplayLabel: "View Trace"
{{- end }}
{{- if .Values.grafana.datasources.pyroscope.enabled }}
      - name: Pyroscope
        type: phlare
        access: proxy
        orgId: 1
        url: {{ .Values.grafana.datasources.pyroscope.url }}
        basicAuth: false
        isDefault: false
        version: 1
        editable: true
        uid: pyroscope
{{- end }}
{{- if .Values.grafana.datasources.mimir.enabled }}
      - name: Mimir
        type: prometheus
        access: proxy
        orgId: 1
        url: {{ .Values.grafana.datasources.mimir.url }}
        basicAuth: false
        isDefault: false
        version: 1
        editable: true
        uid: mimir
{{- end }}
{{- end }}
