---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafana.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.grafana.name }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.grafana.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: http
      port: {{ .Values.grafana.service.port | default 80 }}
      targetPort: {{ .Values.grafana.ports.http | default 3000 }}
      protocol: TCP
  selector:
    app: {{ .Values.grafana.name }}
  type: {{ .Values.grafana.service.type | default .Values.services.type | default "ClusterIP" }}