apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
  namespace: api-app-go
data:
  DB_USER: root
  DB_PASSWORD: admin
  DB_NAME: inventory
  DB_HOST: mysql
  MYSQL_ROOT_PASSWORD: admin # essas duas linhas são para uso do pod do mysql.
  MYSQL_DATABASE: inventory

# Aqui fica armazenado todas as env vars que o container precisa.
# É uma forma mais organizada de usar as env vars., pois se não ficariam todas no deployment.yaml. na seção de env.