apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: api-app-go
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:11.5.2
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: api-app-go
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: grafana
---
apiVersion: v1
kind: ConfigMap # Possibilita usar o Grafana sem login
metadata:
  name: grafana-config
  namespace: api-app-go
data:
  grafana.ini: |
    [auth.anonymous]
    enabled = true
    org_role = Admin

    [security]
    disable_login_form = true
