apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-configmap
  namespace: api-app-go
data:
  init-db.sql: |
    CREATE DATABASE IF NOT EXISTS inventory;
    USE inventory;

    CREATE TABLE IF NOT EXISTS products (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        price DECIMAL(10, 2) NOT NULL,
        quantity INT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    INSERT INTO products (name, price, quantity) VALUES
    ('Product 1', 10.00, 100),
    ('Product 2', 20.00, 200),
    ('Product 3', 30.00, 300);