apiVersion: v1
kind: Service
metadata:
  name: inventory-app-metrics-service
  namespace: api-app-go
spec:
  selector:
    app: inventory-app # Seleciona os Pods com o label app: inventory-app
  ports:
  - protocol: TCP
    port: 2113        # Porta que o Service expõe dentro do cluster
    targetPort: 2113    # Porta do container onde as métricas estão rodando
    name: metrics
  type: ClusterIP