apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: api-app-go
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
    processors:
      batch:
    exporters:
      datadog:
        api:
          key: "${env:DD_API_KEY_GO_LAB}"
          site: datadoghq.com
    extensions:
      health_check: {}
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [datadog]