apiVersion: v1
kind: Service
metadata:
  name: otel-collector-service
  namespace: api-app-go
spec:
  selector:
    app: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317 # Porta do receptor OTLP gRPC
      targetPort: 4317
      protocol: TCP
    - name: health
      port: 13133
      targetPort: 13133
      protocol: TCP
  type: ClusterIP