{
 "title": "dash inventory",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HPA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "HPA Target Metric ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_spec_target_metric{metric_target_type=\"utilization\",horizontalpodautoscaler=\"inventory-app-hpa\",metric_name=\"cpu\"}",
       "legendFormat": "target metric cpu in %"
      },
      {
       "expr": "kube_horizontalpodautoscaler_spec_target_metric{metric_target_type=\"utilization\",horizontalpodautoscaler=\"inventory-app-hpa\",metric_name=\"memory\"}",
       "legendFormat": "target metric memory in %"
      }
     ]
    },
    {
     "title": "HPA ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=\"inventory-app-hpa\"}",
       "legendFormat": "current replicas"
      },
      {
       "expr": "kube_horizontalpodautoscaler_status_desired_replicas{horizontalpodautoscaler=\"inventory-app-hpa\"}",
       "legendFormat": "desired replicas"
      },
      {
       "expr": "kube_horizontalpodautoscaler_spec_min_replicas{horizontalpodautoscaler=\"inventory-app-hpa\"}",
       "legendFormat": "minimum"
      },
      {
       "expr": "kube_horizontalpodautoscaler_spec_max_replicas{horizontalpodautoscaler=\"inventory-app-hpa\"}",
       "legendFormat": "max replicas"
      }
     ]
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uso de CPU em Cores",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{instance=\"inventory-app-metrics-service:2113\"}[$__rate_interval]) )",
       "legendFormat": "Uso de CPU por pod"
      }
     ]
    },
    {
     "title": "Uso de Memória da app inventory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"inventory-app\"}/ 1048576",
       "legendFormat": "Memória em uso"
      }
     ]
    },
    {
     "title": "promhttp_metric_handler_requests_in_flight",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "promhttp_metric_handler_requests_in_flight{job=\"inventory-app\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "http requests total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "http_requests_total{instance=\"inventory-app-metrics-service:2113\"}",
       "legendFormat": "{{method}},{{path}},{{status}}"
      }
     ]
    },
    {
     "title": "Numero de conexões HTTP ativas",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "http_active_connections{job=\"inventory-app\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Quantidade de itens salvos no BD",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "products_in_db{job=\"inventory-app\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "http request duration seconds bucket",
     "type": "histogram",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "http_request_duration_seconds_bucket{job=\"inventory-app\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Número de requisições aos métodos por status code",
     "type": "stat",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "promhttp_metric_handler_requests_total{instance=\"inventory-app-metrics-service:2113\"}",
       "legendFormat": "{{code}}"
      }
     ]
    }
   ]
  }
 ]
}