{
 "title": "Dash Q3",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Inventory API App",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heatmap dos percentis",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_bucket{job=\"inventory-app\"}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uso de Memória da app inventory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"inventory-app\"}/ 1048576",
       "legendFormat": "Memória em uso"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.99,\n  sum(rate(http_request_duration_seconds_bucket{job=\"inventory-app\"}[$__rate_interval])) by (le, job, route)\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"inventory-app\"}[$__rate_interval])) by (le, job, route))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{job=\"inventory-app\"}[$__rate_interval])) by (le, job, route))",
       "legendFormat": "p50 {{route}}"
      }
     ]
    },
    {
     "title": "http requests total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "http_requests_total{instance=\"inventory-app-metrics-service:2113\"}",
       "legendFormat": "{{method}},{{path}},{{status}}"
      }
     ]
    },
    {
     "title": "Uso de CPU em Cores",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{instance=\"inventory-app-metrics-service:2113\"}[$__rate_interval]) )",
       "legendFormat": "Uso de CPU por pod"
      }
     ]
    },
    {
     "title": "Quantidade de itens salvos no BD",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "products_in_db{job=\"inventory-app\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "promhttp_metric_handler_requests_in_flight",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "promhttp_metric_handler_requests_in_flight{job=\"inventory-app\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Número de requisições aos métodos por status code",
     "type": "stat",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 60 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "promhttp_metric_handler_requests_total{instance=\"inventory-app-metrics-service:2113\"}",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Numero de conexões HTTP ativas",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "http_active_connections{job=\"inventory-app\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "http request duration seconds bucket",
     "type": "histogram",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "http_request_duration_seconds_bucket{job=\"inventory-app\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "k8s",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage by container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{namespace=\"api-app-go\",container!=\"\"}",
       "legendFormat": "{{container}} - {{instance}}"
      }
     ]
    },
    {
     "title": "CPU Usage by container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "rate(container_cpu_user_seconds_total{container!=\"\",namespace=\"api-app-go\"}[5m]) + rate(container_cpu_system_seconds_total{container!=\"\",namespace=\"api-app-go\"}[5m])",
       "legendFormat": "{{container}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Container Terminated",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_pod_container_status_terminated{exported_namespace=\"api-app-go\"}",
       "legendFormat": "{{container}} -> Terminated"
      }
     ]
    },
    {
     "title": "Container Running",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_pod_container_status_running{exported_namespace=\"api-app-go\"}",
       "legendFormat": "{{container}} -> Running"
      }
     ]
    },
    {
     "title": "Container Waiting",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_pod_container_status_waiting{exported_namespace=\"api-app-go\"}",
       "legendFormat": "{{container}} -> Waiting"
      }
     ]
    },
    {
     "title": "Container Ready",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{exported_namespace=\"api-app-go\"}",
       "legendFormat": "{{container}} -> Ready"
      }
     ]
    },
    {
     "title": "Reason for last terminated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "kube_pod_container_status_last_terminated_reason{exported_namespace=\"api-app-go\"}",
       "legendFormat": "{{container}} - {{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HPA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory HPA target",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_spec_target_metric{horizontalpodautoscaler=\"inventory-app-hpa\",metric_name=\"memory\",metric_target_type=\"utilization\"}",
       "legendFormat": "target"
      },
      {
       "expr": "kube_horizontalpodautoscaler_status_target_metric{horizontalpodautoscaler=\"inventory-app-hpa\",metric_name=\"memory\",metric_target_type=\"utilization\"}",
       "legendFormat": "utilization"
      }
     ]
    },
    {
     "title": "CPU HPA target",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 10, "y": 25 },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_spec_target_metric{horizontalpodautoscaler=\"inventory-app-hpa\",metric_name=\"cpu\",metric_target_type=\"utilization\"}",
       "legendFormat": "target"
      },
      {
       "expr": "kube_horizontalpodautoscaler_status_target_metric{horizontalpodautoscaler=\"inventory-app-hpa\",metric_name=\"cpu\",metric_target_type=\"utilization\"}",
       "legendFormat": "utilization"
      }
     ]
    },
    {
     "title": "HPA status condition",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_status_condition{horizontalpodautoscaler=\"inventory-app-hpa\",condition=\"ScalingLimited\",status=\"true\"}",
       "legendFormat": "scaling limited"
      },
      {
       "expr": "kube_horizontalpodautoscaler_status_condition{horizontalpodautoscaler=\"inventory-app-hpa\",condition=\"AbleToScale\",status=\"true\"}",
       "legendFormat": "able to scale"
      }
     ]
    },
    {
     "title": "HPA Replicas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 10, "y": 33 },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=\"inventory-app-hpa\"}",
       "legendFormat": "current"
      },
      {
       "expr": "kube_horizontalpodautoscaler_status_desired_replicas{horizontalpodautoscaler=\"inventory-app-hpa\"}",
       "legendFormat": "desired"
      },
      {
       "expr": "kube_horizontalpodautoscaler_spec_max_replicas{horizontalpodautoscaler=\"inventory-app-hpa\"}",
       "legendFormat": "max"
      },
      {
       "expr": "kube_horizontalpodautoscaler_spec_min_replicas{horizontalpodautoscaler=\"inventory-app-hpa\"}",
       "legendFormat": "min"
      }
     ]
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum(\n  rate(container_cpu_user_seconds_total[5m]) + rate(container_cpu_system_seconds_total[5m])\n) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Status do Node em CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "kube_node_status_capacity{resource=\"cpu\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Node Capacity - Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      {
       "expr": "kube_node_status_capacity{resource=\"memory\"}",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs de HPA via EventRouter",
     "type": "logs",
     "description": "melhorar o eventrouter",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{pod=~\"my-eventrouter-.*\"}"
      }
     ]
    },
    {
     "title": "Logs do Ingress Controller",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=\"kube-system\", container=\"controller\"} | regexp `.*?\"(?P<message>[^\"]+)` | line_format \"{{.message}}\""
      }
     ]
    },
    {
     "title": "Logs do etcd",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=\"kube-system\", container=\"etcd\"} | json | line_format \"Level={{.level}} | Message={{.msg}}\""
      }
     ]
    },
    {
     "title": "Logs de todos os pods do ns api-app-go",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=\"api-app-go\"} | logfmt | line_format \"Level={{.level}} | {{.msg}}{{if .err}} | error={{.err}}{{end}}\""
      }
     ]
    },
    {
     "title": "Logs do Kube State Metrics",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 102 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=\"ksm\", container=\"kube-state-metrics\"}\n| regexp `(?P<level>[IWEF])\\d{4}\\s+\\d{2}:\\d{2}:\\d{2}\\.\\d+\\s+\\d+\\s+(?P<source>.*?:\\d+)]\\s+(?P<message>.*)`\n| line_format \"Level={{.level}} | Source={{.source}} | Message={{.message}}\""
      }
     ]
    },
    {
     "title": "Logs do Controller Manager",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 110 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=\"kube-system\", container=\"controller\"}\n| pattern `<client_ip> <_> <_> [<time>] \"<method> <path> <_>\" <status_code> <body_bytes> \"<referrer>\" \"<user_agent>\" <request_length> <request_time> [<upstream_service>] <upstream_addr> <upstream_response_length> <upstream_response_time> <upstream_status> <request_id>`\n| line_format \"Client={{.client_ip}} | {{.method}} {{.path}} | Status: {{.status_code}} | Time: {{.request_time}}s\""
      }
     ]
    },
    {
     "title": "Logs do kube-scheduler",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 118 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=\"kube-system\", container=\"kube-scheduler\"}\n| regexp `(?P<level>[IWEF])\\d{4}\\s+\\d{2}:\\d{2}:\\d{2}\\.\\d+\\s+\\d+\\s+(?P<source>.*?:\\d+)]\\s+(?P<message>.*)`\n| line_format \"Level={{.level}} | Source={{.source}} | Message={{.message}}\""
      }
     ]
    },
    {
     "title": "Logs do CoreDNS",
     "type": "logs",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 125 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=\"kube-system\", container=\"coredns\"} | regexp `\\[(?P<level>\\w+)\\]\\s+(?P<component>[\\w\\/]+):\\s+(?P<message>.*)`"
      }
     ]
    }
   ]
  }
 ]
}