{
 "title": "dash inventory.local",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Heatmap dos percentis",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{job=\"inventory-app\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de Memória da app inventory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"inventory-app\"}/ 1048576",
     "legendFormat": "Memória em uso"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum(rate(http_request_duration_seconds_bucket{job=\"inventory-app\"}[$__rate_interval])) by (le, job, route)\n)",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"inventory-app\"}[$__rate_interval])) by (le, job, route))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{job=\"inventory-app\"}[$__rate_interval])) by (le, job, route))",
     "legendFormat": "p50 {{route}}"
    }
   ]
  },
  {
   "title": "http requests total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "http_requests_total{instance=\"inventory-app-metrics-service:2113\"}",
     "legendFormat": "{{method}},{{path}},{{status}}"
    }
   ]
  },
  {
   "title": "Uso de CPU em Cores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=\"inventory-app-metrics-service:2113\"}[$__rate_interval]) )",
     "legendFormat": "Uso de CPU por pod"
    }
   ]
  },
  {
   "title": "Quantidade de itens salvos no BD",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "products_in_db{job=\"inventory-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "promhttp_metric_handler_requests_in_flight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_in_flight{job=\"inventory-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Número de requisições aos métodos por status code",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{instance=\"inventory-app-metrics-service:2113\"}",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Numero de conexões HTTP ativas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_active_connections{job=\"inventory-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http request duration seconds bucket",
   "type": "histogram",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{job=\"inventory-app\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}