CREATE DATABASE IF NOT EXISTS learning;
USE learning;

CREATE TABLE IF NOT EXISTS data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

INSERT INTO data (name) VALUES ('Produto 1'), ('Produto 2');
